export type MenuItem = {
  name: string;
  price: string;
};

export type MenuCategory = {
  slug: string;
  name: string;
  tagline: string;
  image: string;
  items: MenuItem[];
};

export const menuCategories: MenuCategory[] = [
  {
    slug: "chaat-corner",
    name: "Chaat Corner",
    tagline: "A burst of tangy street flavours.",
    image: "/img/menu/chaat-corner.jpg",
    items: [
      { name: "Pani Puri (8pcs)", price: "£3.50" },
      { name: "Pani Puri Unlimited (3p)", price: "£16.99" },
      { name: "Ragda Puri", price: "£3.00" },
      { name: "Sev Puri", price: "£3.00" },
      { name: "Dahi Puri", price: "£3.00" },
      { name: "Aloo Puri", price: "£3.00" },
      { name: "Papdi Chaat", price: "£4.50" },
      { name: "Samosa Chaat", price: "£5.50" },
      { name: "Bhel Puri Chaat", price: "£4.50" },
      { name: "Kachori Chaat", price: "£5.00" },
      { name: "Bhel Puri", price: "£3.50" },
      { name: "Tikki Chaat", price: "£5.50" },
      { name: "Dahi Vada", price: "£5.00" },
    ],
  },
  {
    slug: "street-bites-special",
    name: "Street Bites Special",
    tagline: "The iconic bun, filled with flavour.",
    image: "/img/menu/street-bites-special.jpg",
    items: [
      { name: "Vada Pav", price: "£2.50" },
      { name: "Butter Vada Pav", price: "£3.00" },
      { name: "Schezwan Vada Pav", price: "£3.00" },
      { name: "Cheese Vada Pav", price: "£3.00" },
      { name: "Masala Fry Vada Pav", price: "£3.50" },
      { name: "Dabeli", price: "£2.00" },
      { name: "Butter Dabeli", price: "£2.50" },
      { name: "Cheese Dabeli", price: "£3.00" },
      { name: "Somosa Pav", price: "£3.00" },
      { name: "Butter Somosa Pav", price: "£3.50" },
      { name: "Schezwan Somosa Pav", price: "£3.50" },
    ],
  },
  {
    slug: "rolls-crispy-bites",
    name: "Rolls & Crispy Bites",
    tagline: "Crispy rolls packed with fresh flavour.",
    image: "/img/menu/rolls-crispy-bites.jpg",
    items: [
      { name: "Paneer Spring Rolls (2pcs)", price: "£2.99" },
      { name: "Spring Rolls (2pcs)", price: "£1.99" },
      { name: "Cheese Puff", price: "£3.50" },
      { name: "Aalu Masala Puff", price: "£3.50" },
    ],
  },
  {
    slug: "burgers-wraps-sandwiches",
    name: "Burgers, Wraps & Sandwiches",
    tagline: "A British twist on the classic burger; classic comfort between slices.",
    image: "/img/menu/burgers-wraps-sandwiches.jpg",
    items: [
      { name: "Veggie Burger", price: "£3.99" },
      { name: "Veggie Wrapped", price: "£4.50" },
      { name: "Paneer Wrap", price: "£5.00" },
      { name: "Omlette Wrap", price: "£5.50" },
      { name: "Paneer Sandwich", price: "£5.00" },
      { name: "Grilled Sandwich", price: "£5.50" },
    ],
  },
  {
    slug: "chips-sides",
    name: "Chips & Sides",
    tagline: "Simple, crispy, and irresistibly good.",
    image: "/img/menu/chips-sides.jpg",
    items: [
      { name: "Plain Chips", price: "£1.99" },
      { name: "Masala Chips", price: "£2.99" },
    ],
  },
  {
    slug: "mains-rice",
    name: "Mains & Rice",
    tagline: "A royal North Indian feast on a plate.",
    image: "/img/menu/mains-rice.jpg",
    items: [
      { name: "Chole Bhature", price: "£7.99" },
      { name: "Chole Puri", price: "£6.99" },
      { name: "Veg Biryani", price: "£7.99" },
      { name: "Chicken Biryani", price: "£8.99" },
      { name: "Tikka Biryani", price: "£9.50" },
      { name: "Hakka Noodles", price: "£6.99" },
      { name: "Veg Manchurian", price: "£7.99" },
      { name: "Jeera Rice", price: "£4.99" },
      { name: "Plain Rice", price: "£3.99" },
    ],
  },
  {
    slug: "momo-station",
    name: "Momo Station",
    tagline: "A Himalayan favourite, loved everywhere.",
    image: "/img/menu/momo-station.jpg",
    items: [
      { name: "Veg Momos (10pcs)", price: "£8.20" },
      { name: "Chicken Momos", price: "£8.99" },
      { name: "Paneer Momos", price: "£8.50" },
      { name: "Fried Momos", price: "£9.99" },
      { name: "Crunchy Kurkure Momos", price: "£8.99" },
    ],
  },
  {
    slug: "dosa-corner",
    name: "Dosa Corner",
    tagline: "Crispy crepe with a South Indian soul.",
    image: "/img/menu/dosa-corner.jpg",
    items: [
      { name: "Plain Dosa", price: "£4.50" },
      { name: "Masala Dosa", price: "£6.50" },
      { name: "Cheese Dosa", price: "£6.50" },
      { name: "Chocolate Dosa", price: "£7.00" },
    ],
  },
  {
    slug: "indian-veg-curries",
    name: "Indian Veg Curries",
    tagline: "A harmony of spices and flavours.",
    image: "/img/menu/indian-veg-curries.jpg",
    items: [
      { name: "Daal Makhani", price: "£8.99" },
      { name: "Muttar Paneer", price: "£9.99" },
      { name: "Aalu Pyaz", price: "£8.99" },
      { name: "Aalu Muttar", price: "£8.99" },
      { name: "Gobi Curry", price: "£8.99" },
      { name: "Daal Tadka", price: "£9.99" },
      { name: "Aalu Chole", price: "£9.99" },
      { name: "Chana Masala", price: "£8.99" },
      { name: "Karahi Paneer", price: "£9.99" },
      { name: "Paneer Bhurji", price: "£10.99" },
      { name: "Mix Veg", price: "£9.99" },
      { name: "Saag", price: "£8.99" },
    ],
  },
  {
    slug: "chicken-curries",
    name: "Chicken Curries",
    tagline: "The warmth of Indian curry classics.",
    image: "/img/menu/chicken-curries.jpg",
    items: [
      { name: "Chicken Masala", price: "£10.99" },
      { name: "Chicken Tikka Masala", price: "£10.99" },
      { name: "Butter Chicken", price: "£10.99" },
      { name: "Keema", price: "£9.99" },
    ],
  },
  {
    slug: "paratha-corner",
    name: "Paratha Corner",
    tagline: "Hand-rolled and griddle-fresh, straight off the tawa.",
    image: "/img/menu/paratha-corner.jpg",
    items: [
      { name: "Aalu Paratha", price: "£3.49" },
      { name: "Gobi Paratha", price: "£3.99" },
      { name: "Paneer Paratha", price: "£3.99" },
      { name: "Cheese Paratha", price: "£3.99" },
    ],
  },
  {
    slug: "tea-coffee",
    name: "Tea & Coffee",
    tagline: "The soul of every Indian street corner.",
    image: "/img/menu/tea-coffee.jpg",
    items: [
      { name: "Chai (S/M)", price: "£1.49 / £2.49" },
      { name: "Karak Chai", price: "£2.99" },
      { name: "Pink Chai", price: "£3.50" },
      { name: "Chai Latte", price: "£3.50" },
      { name: "Espresso (S/D)", price: "£1.29 / £2.49" },
      { name: "Americano", price: "£3.99" },
      { name: "Cappuccino", price: "£3.99" },
      { name: "Latte", price: "£3.99" },
      { name: "Frappe", price: "£3.99" },
      { name: "Mocha", price: "£3.99" },
      { name: "Iced Coffee", price: "£3.99" },
    ],
  },
  {
    slug: "soft-drinks",
    name: "Soft Drinks",
    tagline: "A refreshing break in every sip.",
    image: "/img/menu/soft-drinks.jpg",
    items: [
      { name: "Coca Cola", price: "£1.50" },
      { name: "Fanta", price: "£1.50" },
      { name: "Diet Coke", price: "£1.50" },
      { name: "Zero Sugar Coke", price: "£1.50" },
      { name: "7 Up", price: "£1.50" },
      { name: "Water", price: "£1.20" },
    ],
  },
  {
    slug: "energy-drinks",
    name: "Energy Drinks",
    tagline: "Energy that keeps you going.",
    image: "/img/menu/energy-drinks.jpg",
    items: [
      { name: "Red Bull", price: "£1.70" },
      { name: "Monster", price: "£1.70" },
    ],
  },
  {
    slug: "milkshakes",
    name: "Milkshakes",
    tagline: "Smooth, cool, and naturally comforting.",
    image: "/img/menu/milkshakes.jpg",
    items: [
      { name: "Mango Milkshake", price: "£4.50" },
      { name: "Banana Milkshake", price: "£4.50" },
      { name: "Oreo Milkshake", price: "£5.00" },
      { name: "Strawberry Milkshake", price: "£5.50" },
      { name: "Nutella Milkshake", price: "£6.00" },
      { name: "Biscoff Milkshake", price: "£6.00" },
      { name: "Ferrero Rocher Milkshake", price: "£6.00" },
    ],
  },
];
